db_class(a,'Object').
db_class(b,a).
db_class(c,b).
db_class(d,b).
db_class(e,b).

db_method(a,m1,[int,real]->boolean).
db_method(a,m2,[c]->boolean).
db_method(b,m3,[a]->void).
db_method(b,f,[int,d]->int).
db_method(c,f2,[c,d]->int).
db_method(c,m2,[d]->void).
db_method(d,h,[int]->void).
db_method(d,m1,[e,b]->boolean).
db_method(e,h,[int]->void).
db_method(e,m1,[int,real]->boolean).

db_field(a,x1:int).
db_field(a,y1:int).
db_field(a,z1:b).
db_field(b,w1:double).
db_field(b,x1:int).
db_field(b,x2:int).
db_field(b,x3:c).
db_field(c,z1:d).
db_field(c,z2:d).
db_field(d,y1:c).
db_field(d,z1:a).
db_field(e,y1:c).
db_field(e,z1:a).